### ISSUE TITLE
#packages/ URL fragment is handled incorrectly

### ISSUE THREAD

**Issue by Fingercomp** [hel-repo/hel-face#1]
### Expected behaviour

The app should redirect back to the package list if the fragment is incorrect.
### Actual behaviour

An error is shown, telling about unexpected message.
### Screenshots

![Scr#1](https://i.imgur.com/v2mSQVg.png)

**Comment by MoonlightOwl** [comment]
Got it. The error happens due to library problems with parsing URLs with trailing slash.
Fixin...

**Comment by Fingercomp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Некорректно обрабатывается /#packages/](https://trello.com/c/2YyHGgGk/106-packages)

**Comment by MoonlightOwl** [comment]
Done!
