### ISSUE TITLE
Error is shown even if everything is ok

### ISSUE THREAD

**Issue by Fingercomp** [hel-repo/hel-face#2]
### Steps to reproduce
1. Go to `/#packages/hpm` (or any other valid package name).
2. Open `/#packages/any-package-that-does-not-exist`. An error message is shown, as expected.
3. Open details of any existing package (e.g., `/#packages/holo`).
### Expected behaviour

The error message should become hidden.
### Actual behaviour

The error message is still unexpectedly shown, although no errors have occured.
### Screenshots
- **Step 1**: ![Step 1](https://i.imgur.com/S51uQMs.png)
- **Step 2**: ![Step 2](https://i.imgur.com/kZaZdz5.png)
- **Step 3**: ![Step 3](https://i.imgur.com/rbiJV0T.png)

**Comment by MoonlightOwl** [comment]
Shame on me :flushed:
I'm not cleaning error field after successful action.
Fixin...

**Comment by Fingercomp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ошибка показывается, даже если усё норм](https://trello.com/c/3KWfwJTg/108--)
