### ISSUE TITLE
Handle common errors differently than uncommon ones

### ISSUE THREAD

**Issue by Fingercomp** [hel-repo/hel-face#3]
### Details

This is how "package not found" message looks right now:
![Screenshot](https://i.imgur.com/JqcerV5.png)

It doesn't look user-friendly yet. Such common errors as 404, 403 should be handled differently than other errors.
### Proposed changes
- [x] Do not show a scary error message in the header.
- [x] Display a card (looking a little differently than a regular card with package details, for example, set the bg color to red) with a human-readable error description and common things that may have caused the error.

**Comment by Fingercomp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Обрабатывать частые ошибки более юзер-френдли](https://trello.com/c/Ct5R1tBy/117--)

**Comment by MoonlightOwl** [comment]
Agreed. Was thinking about this already.

**Comment by MoonlightOwl** [comment]
Done (24e986a).
