### ISSUE TITLE
Tag chips overlap the title

### ISSUE THREAD

**Issue by Fingercomp** [hel-repo/hel-face#4]
### Steps to reproduce
1. Shrink the width of browser.
### Expected behaviour

The tags should go on the next line.
### Actual behaviour

The tags overlap the title.
### Screenshots
- ![Screenshot](https://i.imgur.com/YfpAu9p.png)

**Comment by Fingercomp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Чипсы налезают на заголовок карточки](https://trello.com/c/6FFdOIvn/148--)

**Comment by MoonlightOwl** [comment]
Fixed!
Now it looks like this:
![Screenshot](http://i.imgur.com/K6IzcM0.png)
