### ISSUE TITLE
Waterfall is broken

### ISSUE THREAD

**Issue by Fingercomp** [hel-repo/hel-face#5]
### Details

If the height of the content is slightly more than the height of viewport, the header will roll up when scrolled down. But the scrollbar disappears after that, so there's no way to, erm, expand the header back.
### Proposed solution

Remove the waterfall attribute, and reduce the bottom padding of the header.

**Comment by Fingercomp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Вотерфолл ведёт себя странно](https://trello.com/c/ZGogLmWH/147--)

**Comment by MoonlightOwl** [comment]
Since the header became lower and the waterfall is no longer necessary - fixxed!
